### ISSUE TITLE
dataloader的droplast问题

### ISSUE THREAD

**Issue by ccloud0525** [zezhishao/BasicTS#125]
请问如何控制训练集，验证集，测试集drop_last为True or False。您跑实验时候这三部分默认是True还是False呢

**Comment by zezhishao** [comment]
BasicTS/easytorch目前不支持 drop_last的设置，，默认为 False。

BasicTS 没有对数据进行填充，所以理论上来说不需要 drop 最后一组 Batch。

**Comment by zezhishao** [comment]
假如 BasicTS 对您有用，别忘了点个 stars～

对这个设置有疑问或者确实很有需求的话，欢迎继续留言。必要的话，我可以把这个设置加入进来。
