### ISSUE TITLE
STGCN 模型不能跑第二次

### ISSUE THREAD

**Issue by zixu2023** [zezhishao/BasicTS#126]
您好，为什么我的STGCN跑完一次结果以后就不能再跑了，就是之后跑的结果都会保存在第一次的跑完的文件夹里，以至于程序没开始运行就结束吧，然后打印的开头保存在了第一次生成的文件夹中，而别的模型没有这个问题

**Comment by zezhishao** [comment]
这是因为您的Config文件没有任何变化。 BasicTS 根据 Config 文件的 md5 值自动获取 checkpoint 文件夹，并自动resume 训练。假如确实做了一些修改，您最好也修改 Config 文件。例如，`CFG.DESCRIPTION = "XXX (model name) Configurate with YYY (new modification)"`。
