### ISSUE TITLE
您好，请教一下模型训练好后如何获取预测值与真实值的数据

### ISSUE THREAD

**Issue by KDP-wayofdata** [zezhishao/BasicTS#129]

**Comment by zezhishao** [comment]
您是要获取测试集的预测值和真实值？

**Comment by KDP-wayofdata** [comment]
是的

**Comment by zezhishao** [comment]
可以参考这个[test](https://github.com/zezhishao/BasicTS/blob/318f223727ec140333500e4f7cbbd35cdbe64506/basicts/runners/base_tsf_runner.py#L415)函数。
有其他疑问也欢迎继续讨论。

**Comment by KDP-wayofdata** [comment]
调用这个函数需要什么指令，可以直接输出为csv格式嘛

**Comment by zezhishao** [comment]
`experiments/inference.py`是一个推理脚本，加载训练好的 checkpoint 并在测试集上推理。
你在 test 函数结束之前加几行代码，把 test 函数里面的 returns_all存储到本地，然后运行这个脚本。
returns_all是一个字典，prediction 是你的预测、target 是真值，都是 torch.Tensor，具体如何保存、保存成什么格式可以自己选。
