### ISSUE TITLE
the 'package' argument is required to perform a relative import for '.AGCRN_arch.AGCN'

### ISSUE THREAD

**Issue by NoahWangc** [zezhishao/BasicTS#15]
![image](https://user-images.githubusercontent.com/42688858/187137848-4923a4b9-3f4e-4be9-8144-0022ea195017.png)
I encountered this problem while running the code, and I don't know how to solve it. I look forward to your reply, thank you!

**Comment by zezhishao** [comment]
I cannot reproduce the result in the latest version of the BasicTS. Could you give me more information?

**Comment by NoahWangc** [comment]
> I cannot reproduce the result in the latest version of the BasicTS. Could you give me more information?

I solved this problem. Thank you for your help.
BasicTS is an exciting job. It unifies most of the most advanced Baseline. I think it can promote the development of this community. I hope it will further unify more baselines. such as Z-GCNETs and STGODE.

**Comment by zezhishao** [comment]
Thanks for your advice!
I will add more baselines in the future. However, I don't have much time, so the process can be slow.
Therefore, I'm currently refactoring BasicTS to make it easier for users to use and contribute. 
Welcome to contribute to BasicTS in the future to make the community better!
