### ISSUE TITLE
Train problem,，停在这里没反应

### ISSUE THREAD

**Issue by byq-luo** [zezhishao/BasicTS#34]
2022-11-02 11:05:17,415 - easytorch - INFO - Building model.
C:\Users\luo\anaconda3\envs\basicts\lib\site-packages\torch\cuda\__init__.py:143: UserWarning:
NVIDIA GeForce RTX 3050 Ti Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3050 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2022-11-02 11:05:17,481 - easytorch-training - INFO - Initializing training.
2022-11-02 11:05:17,482 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 5.0}
2022-11-02 11:05:17,482 - easytorch-training - INFO - Building training data loader.
train len: 23974
2022-11-02 11:05:17,583 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.002
    weight_decay: 1e-05
)
2022-11-02 11:05:17,584 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x000001F12B3E4908>
2022-11-02 11:05:17,590 - easytorch-training - INFO - Initializing validation.
2022-11-02 11:05:17,590 - easytorch-training - INFO - Building val data loader.
val len: 3425
test len: 6850
2022-11-02 11:05:17,866 - easytorch-training - INFO - Epoch 1 / 100
  0%|                                                                                          | 0/750 [00:00<?, ?it/s]

**Comment by zezhishao** [comment]
似乎您的GPU版本的PyTorch没安装好，您可以使用`nvidia-smi`查看GPU的使用情况。

**Comment by byq-luo** [comment]
> 似乎您的GPU版本的PyTorch没安装好，您可以使用`nvidia-smi`查看GPU的使用情况。

torch gpu 用torch.cuda.is_available() 测试没问题。但是看nvidia-smi是内存一直在增加，显卡是0%

**Comment by byq-luo** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.98       Driver Version: 512.98       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8     3W /  N/A |    861MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3960      C   ...3\envs\basicts\python.exe    N/A      |
|    0   N/A  N/A      9856      C   ...3\envs\basicts\python.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by byq-luo** [comment]
win10 没有安装cuda cudnn 有影响么

**Comment by zezhishao** [comment]
抱歉，我windows跑过代码，所以我也不清楚。

**Comment by byq-luo** [comment]
MLP

**Comment by zezhishao** [comment]
Please check https://discuss.pytorch.org/t/nvidia-geforce-rtx-3050-ti-laptop-gpu-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/143837/3.

**Comment by zezhishao** [comment]
似乎就是CUDA没装好，可以按照PyTorch官网的Instruction安装。

**Comment by byq-luo** [comment]
好的 我试试 谢谢了

**Comment by zezhishao** [comment]
不客气，有其他问题欢迎再创建一个Issue。

**Comment by byq-luo** [comment]
(base) PS D:\code\BasicTS\datasets\METR-LA> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_20:11:50_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0
(base) PS D:\code\BasicTS\datasets\METR-LA>  

是不是cuda与pytorch版本不对应。pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html
我装的这个。

**Comment by zezhishao** [comment]
建议遵循BasicTS中的依赖的安装方式和版本，其他版本的兼容性问题并未测试，需要自行查询资料。

**Comment by byq-luo** [comment]
好的

**Comment by zezhishao** [comment]
https://discuss.pytorch.org/t/nvidia-geforce-rtx-3050-ti-laptop-gpu-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/143837/3
建议参考这个，应该能解决你的问题。
