### ISSUE TITLE
Can you add a prediction module?

### ISSUE THREAD

**Issue by xiewenqiang666** [zezhishao/BasicTS#36]
We want to test with a trained model, but the code does not provide this functionality.

**Comment by zezhishao** [comment]
You can refer to [here](https://github.com/zezhishao/BasicTS/blob/master/tests/test_inference.py).

Set `cfg` to the path to your configuration, and set `ckpt` to the path to your pre-trained model.

**Comment by xiewenqiang666** [comment]
Thank you very much for your patient guidance.
