### ISSUE TITLE
[TODO: 清理注释文档] 数据集问题

### ISSUE THREAD

**Issue by Azusa-Yuan** [zezhishao/BasicTS#41]
PEMS04 08 这类数据集原始数据是包括三个通道flow, speed, occupancy。在处理数据集的时候，只取了第一通道也就是flow，然后在脚本描述中出现了矛盾，所以我不是很清楚，在PEMS04 08这些数据集上，默认是预测速度还是流量
- Channels (features): three channels [traffic flow, time of day, day of week]
- Target: predict the traffic speed of the future 12 time steps.[here](https://github.com/zezhishao/BasicTS/blob/44a4fc5c5a01069eb21e66c9245f93780009df90/scripts/data_preparation/PEMS04/generate_training_data.py#L21)

**Comment by zezhishao** [comment]
抱歉，这个是一些typos。

METR-LA和PEMS-BAY是交通流量；
PEMS0X数据集都是交通流。
这个设置是定死不动的，而注释里面的内容可能会出现一些错误。

或许在其他的注释中也存在着这样的typo。。。
我会找时间清理一下，假如您发现了类似的错误，也欢迎PR。

**Comment by Azusa-Yuan** [comment]
> 抱歉，这个是一些typos。
> 
> METR-LA和PEMS-BAY是交通流量； PEMS0X数据集都是交通流。 这个设置是定死不动的，而注释里面的内容可能会出现一些错误。
> 
> 或许在其他的注释中也存在着这样的typo。。。 我会找时间清理一下，假如您发现了类似的错误，也欢迎PR。

印象中METR-LA和PEMS-BAY只有交通速度。好的，我明白了

**Comment by zezhishao** [comment]
啊。。。抱歉脑子糊涂了，写反了。已经更正。
METR-LA、PEMS-BAY是交通速度，PEMS0X是交通流量。

**Comment by Azusa-Yuan** [comment]
> 啊。。。抱歉脑子糊涂了，写反了。已经更正。 METR-LA、PEMS-BAY是交通速度，PEMS0X是交通流量。

没事没事，我也经常糊涂，非常感谢您的迅速回复
