### ISSUE TITLE
Unify data pre-processing of traffic datasets and LSTF datasets.

### ISSUE THREAD

**Issue by zezhishao** [zezhishao/BasicTS#43]

**Comment by superarthurlx** [comment]
ETT datasets has a fix train-test split ratio according to the DLinear's code. Others like traffic,weather,electricity and exchange rate also have ratio issues but less essential.

**Comment by zezhishao** [comment]
Hi, @superarthurlx , thank you for your suggestion.

BasicTS follows the setting of ETT datasets from Informer, where the datasets are originally released, and the train/valid/test ratio is 0.6/0.2/0.2. 
In addition, BasicTS uses the entire ETT dataset, while other works usually use part of it.

By the way, the situation of LSTF datasets like ETT and Weather is a bit complicated, and here are more situations that may affect your use:
- LSTF works usually calculate metrics based on normalized data. However, the correct way is to calculate based on re-normalized data (BasicTS follows this way).
- ETT and other datasets may have a large amount of non-abnormal 0 values, which may affect the effectiveness of the MAPE.

Considering these special situations, the results of BasicTS on these datasets might be different from the original papers.

**Comment by zezhishao** [comment]
I am trying to sort out these situations and clean the code and make detailed explanations.

**Comment by superarthurlx** [comment]
> 

![image](https://user-images.githubusercontent.com/40826115/223647808-8bd16d49-f0c1-452f-b4fa-568b1da4c70d.png)
Sorry I didn't make it clear, my point is ETT datasets use a fix number to split train/valid/test sets, not split them by ratios with the whole datasets. btw I manage to use BasicTS to reproduce the experimental results of the Dlinear's, thx for your great work.

**Comment by zezhishao** [comment]
Yes, I see what you mean. 
This approach is equivalent to taking the first 20 months of the ETT dataset and dividing the dataset at a ratio of 0.6/0.2/0.2 (12 months/4 months/4 months).

**Comment by zezhishao** [comment]
Done. 
Commit: 7a7f97088df685d39342a33b4424193b3d927c2f
