### ISSUE TITLE
Out of memory when handling large scale datasets.

### ISSUE THREAD

**Issue by zezhishao** [zezhishao/BasicTS#46]
https://github.com/zezhishao/BasicTS/blob/f02703912318f334510bfe4d75464ad5c7617dec/basicts/runners/base_tsf_runner.py#L291

**Comment by superarthurlx** [comment]
![image](https://user-images.githubusercontent.com/40826115/223630535-3d1df1ee-8ce8-48fd-be8a-8a01d3f0a842.png)
one of possible solutions.

**Comment by zezhishao** [comment]
Thanks for your advice~
