### ISSUE TITLE
pycharm can't debug

### ISSUE THREAD

**Issue by lijinrun** [zezhishao/BasicTS#52]
你好，非常感谢你的工作，我在使用pycharm连接远程服务器debug代码的时候，会卡住，但是用vscode就没问题，想请教一下是什么原因。例如以下这种情况：
![image](https://user-images.githubusercontent.com/49092533/237039450-730d8987-8ff0-41b4-8650-3c88c96b036f.png)
我在stid_arch.py文件下打了一个断点，然后运行example/run.py，得到上图的结果，但是我点击步过就卡住了，如下图所示
![image](https://user-images.githubusercontent.com/49092533/237039818-0893e886-3d2f-443c-b003-eb6a8b7da990.png)
![image](https://user-images.githubusercontent.com/49092533/237039844-d57a44cc-ae81-413b-a000-29c892d415e8.png)
用vscode就不存在这个问题，这是怎么回事呢？

**Comment by zezhishao** [comment]
抱歉，我没有用过PyCharm远程debug。

**Comment by lichuan210** [comment]
![image](https://github.com/zezhishao/BasicTS/assets/83169304/7d889290-6089-4b0e-ba3f-18aba5833ded)
Changing the settings of pycharm debugger as shown in the figure may help.
