### ISSUE TITLE
How to use bash code to tune hyperparameters?

### ISSUE THREAD

**Issue by yuqinie98** [zezhishao/BasicTS#56]
Hello, congrats for the great work! I was trying to do hyperparameter tuning of my model, using a sh file to pass the arguments into the py file (using argparse). 

However, if I have a script, say "run.sh", it will run the "example/run.py", and then "example/run.py" will try to get the hyperparameters in "examples/Triformer/Triformer_ETTh1.py". 

Now I want to pass the hyperparameters from "run.sh" to "examples/Triformer/Triformer_ETTh1.py". But it seems I can only pass arguments to the "example/run.py". Since the parameters are stored in "examples/Triformer/Triformer_ETTh1.py", which is the file I want to modify, could you kindly suggest on that? Thanks very much for your time!

**Comment by zezhishao** [comment]
You can copy several your config files, and use different hyper-parameters.
For example, Triformer _etth1_lr_0001.py and Triformer
_etth1_lr_0002.py.

**Comment by yuqinie98** [comment]
I see, that is indeed a clever way to do it. Thanks!

**Comment by zezhishao** [comment]
You're welcome! If you have any other questions or suggestions, feel free to create a new issue.

**Comment by malay-gaherwar** [comment]
How were you able to carry out Hyperparameter tuning? I'm trying to do so for my dataset using one of the BasicTS models using Optuna but unsure as the actual training is being done by easy-torch.

**Comment by zezhishao** [comment]
We are currently not familiar with Optuna or other AutoML tools, so BasicTS does not officially support training with these tools at this time. However, we are actively learning about these tools and exploring ways to integrate them into BasicTS in the future.
