### ISSUE TITLE
关于easytorch的问题

### ISSUE THREAD

**Issue by zhoujiajuly** [zezhishao/BasicTS#6]
你好，
我想问一下，我安装了easytorch，但是我运行的时候还是会显示：

from easytorch.easytorch import launch_training
ImportError: cannot import name 'launch_training' from 'easytorch.easytorch' 

我尝试了好多，还是没有成功。想请教一下作者这到底是怎么回事。

**Comment by zezhishao** [comment]
感谢您的提问！

我更新了easytorch的调用方式，您通过`pip install easy-torch`安装EasyTorch之后应该就可以正常运行了。
具体的运行方法可以参考更新后的README.md。

---

假如有任何疑问和建议，欢迎提问和留言～
