### ISSUE TITLE
How to implement single-step forecasting in DGCRN？

### ISSUE THREAD

**Issue by zhishiouo** [zezhishao/BasicTS#61]
Why is my single-step prediction accuracy low?

**Comment by zhishiouo** [comment]
Is there a requirement for input and output step size?

**Comment by zezhishao** [comment]
> Is there a requirement for input and output step size?

Yes, here are the steps:
- Generate samples: `python scripts/data_preparation/${DATASET_NAME}/generate_training_data.py --history_seq_len 12 future_seq_len 1`
- Change the `CFG.DATASET_OUTPUT_LEN` and `CFG.DATASET_INPUT_LEN` in the config files.
- Change training parameters (optional). For example, for single step forecasting, the curriculum learning is no longer useful, and you can just delete the `CFG.TRAIN.CL` dict.
- Change the model parameters (optional) The parameters of the model need to read its original paper to determine how to modify it.

**Comment by zhishiouo** [comment]
Modified by the above method, but the prediction accuracy is not ideal.Not even as good as multi-step prediction.

**Comment by zhishiouo** [comment]
And just delete the dict.CFG.TRAIN.CL,  but an error occurred in the program.I modify CFG.TRAIN.CL.PREDICTION_LENGTH = 1，It can run, but with poor accuracy

**Comment by zezhishao** [comment]
> And just delete the dict.CFG.TRAIN.CL, but an error occurred in the program.

More info?

**Comment by zezhishao** [comment]
BTW, kindly note that the acc of single step prediction does not have to be better than multi-step prediction at horizon 1.

**Comment by zezhishao** [comment]
> And just delete the dict.CFG.TRAIN.CL, but an error occurred in the program.

The reason is that the DGCRN model requires the implementation of CL (for details, please refer to its paper). Please use the following configuration:

```python
...
CFG.DATASET_INPUT_LEN = 12
CFG.DATASET_OUTPUT_LEN = 1 # *** change the DATASET_OUTPUT_LEN from 12 to 1 ***
CFG.MODEL.PARAM = {
    "gcn_depth": 2,
    "num_nodes": 207,
    "predefined_A": [torch.Tensor(_) for _ in adj_mx],
    "dropout": 0.3,
    "subgraph_size": 20,
    "node_dim": 40,
    "middle_dim": 2,
    "seq_length": 1, # *** change the seq_length from 12 to 1 ***
    "in_dim": 2,
    "list_weight": [0.05, 0.95, 0.95],
    "tanhalpha": 3,
    "cl_decay_steps": 4000,
    "rnn_size": 64,
    "hyperGNN_dim": 16
}
...
## curriculum learning
CFG.TRAIN.CL = EasyDict()
CFG.TRAIN.CL.WARM_EPOCHS = 0
CFG.TRAIN.CL.CL_EPOCHS = 1
CFG.TRAIN.CL.PREDICTION_LENGTH  = 1
...
# ***add the evaluation horizon configs***
CFG.EVAL = EasyDict()
CFG.EVAL.HORIZONS = [1]
```

**Comment by zhishiouo** [comment]
thanks

**Comment by zhishiouo** [comment]
I want to ask you the reason that the acc of single-step prediction is not necessarily better than the acc of multi-step prediction at Horizon 1.  And Why the acc of multi-step prediction at Horizon 1 does not decline with iteration.
![image](https://github.com/zezhishao/BasicTS/assets/113890306/f1f31794-d45e-4f74-b573-d758785edc66)
![image](https://github.com/zezhishao/BasicTS/assets/113890306/d1f9316f-b432-40e3-8976-be42ae7b05a5)
