### ISSUE TITLE
I want to ask you the reason that the acc of single-step prediction is not necessarily better than the acc of multi-step prediction at Horizon 1.  And Why the acc of multi-step prediction at Horizon 1 does not decline with iteration.

### ISSUE THREAD

**Issue by zhishiouo** [zezhishao/BasicTS#62]
I want to ask you the reason that the acc of single-step prediction is not necessarily better than the acc of multi-step prediction at Horizon 1.  And Why the acc of multi-step prediction at Horizon 1 does not decline with iteration.
![image](https://github.com/zezhishao/BasicTS/assets/113890306/f1f31794-d45e-4f74-b573-d758785edc66)
![image](https://github.com/zezhishao/BasicTS/assets/113890306/d1f9316f-b432-40e3-8976-be42ae7b05a5)

_Originally posted by @zhishiouo in https://github.com/zezhishao/BasicTS/issues/61#issuecomment-1659459348_

**Comment by zezhishao** [comment]
> The reason that the acc of single-step prediction is not necessarily better than the acc of multi-step prediction at Horizon 1.

This is a big question, and I dont have a good answer. Intuitively, redefining the length of target time series is equivalent to redesigning machine learning tasks. As a machine learning task, I dont know whether there is necessary relationship between the difficulty of single-step prediction and multi-step prediction. 

> And Why the acc of multi-step prediction at Horizon 1 does not decline with iteration.

Why should this be so?

BTW, I think these questions are out-of-scope of this repository, and these questions are research problems.
