### ISSUE TITLE
怎么在DGCRN的消融实验中删除time of day 进行实验

### ISSUE THREAD

**Issue by zhishiouo** [zezhishao/BasicTS#63]
单纯在generate_training_data.py中选择False会报错

**Comment by zezhishao** [comment]
感谢您的report，我查一下。

**Comment by zezhishao** [comment]
您好，您应该需要根据DGCRN论文中的描述修改模型结构。
具体来说，是修改DGCRN架构中的[time_of_day](https://github.com/zezhishao/BasicTS/blob/d2059631c7353da56960ac97985b5187c1cb26b1/basicts/archs/arch_zoo/dgcrn_arch/dgcrn_arch.py#L196)。
BasicTS的配置无需改变。

**Comment by zhishiouo** [comment]
请问具体要修改哪部分呢

**Comment by zezhishao** [comment]
这个我也不清楚，需要根据论文的要求来。

**Comment by zhishiouo** [comment]
好的
