### ISSUE TITLE
Data visualization issues

### ISSUE THREAD

**Issue by ZPFPHD** [zezhishao/BasicTS#64]
Hello author, how can I export predicted values in BasicTS?I saw scripts/data_ Visualization/data_ Visualization.ipynb, but this program can only see real values, no predicted values。
作者你好，我如何导出预测值？在可视化程序中只能看到真实值的历史数据和未来数据，没有预测值的程序。感谢回答！

**Comment by zezhishao** [comment]
嘿，您好。data_visualization.ipynb是用来在设计模型之前检查数据的，确实是只能看到历史数据和未来数据。
目前想要可视化预测值的话，会比较复杂，需要您手动做一些操作。
概括来说，您需要先训练好您的模型，然后修改runner从而保存历史数据、未来数据、预测数据(稍后详细讨论），然后执行[inference脚本](https://github.com/zezhishao/BasicTS/blob/master/inference/inference.py)进行推理。
这样在您运行推理之后，就会保存下来预测结果，然后再自己写脚本进行可视化。

以下是更详细的说明：
- 1. 训练您的模型，达到最后，得到checkpoint。
- 2. 您可以修改[`runner`的`test`函数](https://github.com/zezhishao/BasicTS/blob/d2059631c7353da56960ac97985b5187c1cb26b1/basicts/runners/base_tsf_runner.py#L343C1-L363C46)，从而在之后的推理过程中保存想要的数据。
下面是一个示例：
```diff
    @torch.no_grad()
    @master_only
    def test(self):
        """Evaluate the model.

        Args:
            train_epoch (int, optional): current epoch if in training process.
        """

        # test loop
        prediction = []
        real_value = []
+       history = []
        for _, data in enumerate(self.test_data_loader):
            forward_return = self.forward(data, epoch=None, iter_num=None, train=False)
            prediction.append(forward_return[0])        # preds = forward_return[0]
            real_value.append(forward_return[1])        # testy = forward_return[1]
+           history.append(data[1][..., [0]]) # new line
        prediction = torch.cat(prediction, dim=0)
        real_value = torch.cat(real_value, dim=0)
+       history = torch.cat(history, dim=0)
        # re-scale data
        prediction = self.rescale_data(prediction) if self.if_rescale else prediction
        real_value = self.rescale_data(real_value) if self.if_rescale else real_value
+       history = self.rescale_data(history) if self.if_rescale else history
+       # save prediction, real_value and history
+       import pickle
+       with open("prediction.pkl", "wb") as f:
+           pickle.dump(prediction.detach().cpu(), f)
+       with open("real_value.pkl", "wb") as f:
+           pickle.dump(real_value.detach().cpu(), f)
+       with open("history.pkl", "wb") as f:
+           pickle.dump(history.detach().cpu(), f)
+       # evaluate
        self.evaluate(prediction, real_value)
```
- iii. 运行[inference脚本](https://github.com/zezhishao/BasicTS/blob/master/inference/inference.py)。

上述步骤结束后，您会在project目录下的到这三个数据。然后您可以写一个单独的脚本读取他们并进行可视化。
它们的维度都是`[B, L, N, 1]`, `B`是样本的数量，`N`是时间序列的数量，`L`是每个样本预测的长度/历史的长度。

后续BasicTS会考虑加入自动保存预测结果的选项。

**Comment by ZPFPHD** [comment]
感谢！已经导出了数据，但我发现数据是归一化后的，如何反归一化呢？

**Comment by zezhishao** [comment]
您是在跑长序列预测模型是吗？
Config文件中`CFG.RESCALE = False`控制着是否进行反归一化。
您可以将这个选项修改成`True`，就可以在推理的时候自动反归一化。
需要注意的是，`RESCALE`参数会同时影响训练、测试、验证。您要是只想在推理的时候反归一化，训练的时候保持这些模型论文中描述的默认设置，那么在训练过程中还是得将`CFG.RESCALE=False`。

**Comment by ZPFPHD** [comment]
十分感谢！
