### ISSUE TITLE
请教一下关于xlsx数据，date部分是如何处理的

### ISSUE THREAD

**Issue by yangjq713** [zezhishao/BasicTS#70]
air quaility数据中没有date这个字段了，想请教一下现在这个xlsx中每条数据和原始的时间戳之间的对应关系

**Comment by zezhishao** [comment]
您好，对于模型来说，不同的日期只需要是离散的、可区分的即可。
例如，我们可以给周一到周日赋予0～6七个数字，但也可以给他们赋予[6, 0, 1, 2, 3, 4, 5]。对于模型来说没有区别。
所以只需要知道数据集的采样率，并且数据集是保持这个采样率连续采样的，那么就可以假设第一个点是每天的第一个点、每周的第一个点。
