### ISSUE TITLE
关于WAPE评价指标

### ISSUE THREAD

**Issue by ZhangYuan1998** [zezhishao/BasicTS#73]
Zezhi Shao, 

再次感谢您开源的代码！

您好，在此咨询您一些问题。

为什么额外选择WAPE作为评价指标？

WAPE和WMAPE公式分别如下：
![image](https://github.com/zezhishao/BasicTS/assets/102887477/a852cfb8-9686-4d63-a5f9-cb275814887e)
![image](https://github.com/zezhishao/BasicTS/assets/102887477/76eb56f4-f614-4112-a539-56bf1f9d5da7)
从公式来看，WAPE相对于WMAPE少了权重项，是不是可以理解是WMAPE的特殊形式？

此外，在时间序列预测的背景下，WAPE作为评价指标又有哪些好处?
是不是可以降低对于预测数值的敏感性，尤其在多变量时间序列预测任务上，不同变量其数值上下限可能有很大差异，是不是用WAPE可以降低这些影响？

期待您的回复！
祝您万事顺遂！

**Comment by zezhishao** [comment]
您好，WAPE可以看作WMAPE的一个特例，WMAPE是为了解决WAPE和MAPE无法对不同的样本赋予不同权重的问题。
选用WAPE是为了解决MAPE受到0值影响较大的问题。

总的来说，BasicTS的evaluation setting是：在re-normalized数据上，同时计算绝对误差（MAE、MSE、RMSE等）和相对误差（MAPE、WAPE）等。当然，也可以添加更多的metrics。

**Comment by ZhangYuan1998** [comment]
好的感谢您的回复！
