### ISSUE TITLE
请教测试结果最佳模型指标问题

### ISSUE THREAD

**Issue by tongnie** [zezhishao/BasicTS#78]
您好！十分感谢您的工作！关于模型测试结果有点疑问想请教下：

模型最终训练完成时如何显示最佳预测精度呢？即best model result的结果。目前BasicTS的log中是否是根据每个epoch找到val_mae最低的模型保存，然后用该checkpoint做多步预测计算平均test MAE呢？
如何在整个训练结束时打印出整个训练过程中val_mae最低模型的测试集预测精度指标呢？

例如下图所示，我发现在训练最后一轮时显示'Evaluate best model on test data'的结果并不是val_mae最低的模型的结果：
训练最后一轮时：
![image](https://github.com/zezhishao/BasicTS/assets/97451044/e1691e50-9358-4b3a-9341-8e65ad8b6541)
训练过程中间某一步：
![image](https://github.com/zezhishao/BasicTS/assets/97451044/2779f0d2-f241-4a91-ad1d-be3a0d9d41e0)

请问在BasicTS中是如何确定当前的best model以及如何查看最终的评价结果呢？

期待您的回复！

**Comment by zezhishao** [comment]
当指标（默认为MAE）下降地时候，BasicTS会默认打印出一行log：
```
 Checkpoint checkpoints/MODEL_EPOCH/MD5/MODEL_best_val_MAE.pt saved
```
因此，你可以直接搜索搜索'best_'（有个下划线），找到最后一个位置，就是最好的模型了。

**Comment by tongnie** [comment]
感谢您的帮助！
