### ISSUE TITLE
请问我们测试长度为{96,192,336,720}的历史数据，报告最佳表现。

### ISSUE THREAD

**Issue by qiu69** [zezhishao/BasicTS#82]
![image](https://github.com/zezhishao/BasicTS/assets/82441982/56018682-ed6a-4701-a3ee-db750f25fa23)
这个表当中的最优，指的是未来数据的长度设置为336，测试长度为{96,192,336,720}的历史数据中最好的一个情况？换句话说同一个数据集，每个算法的结果可能是在不同历史数据长度上得到的吗？
![image](https://github.com/zezhishao/BasicTS/assets/82441982/b094c44f-5a66-458e-99c8-85685cd5f869)
配置里面历史长度都是336，因为336性能最优吗还是统一都这样写。但在benchmark测试时候是把{96,192,336,720}每种情况都测一遍？
谢谢

**Comment by zezhishao** [comment]
> 这个表当中的最优，指的是未来数据的长度设置为336，测试长度为{96,192,336,720}的历史数据中最好的一个情况？换句话说同一个数据集，每个算法的结果可能是在不同历史数据长度上得到的吗？
是的，这个主要是follow了现有的长序列工作的一些设置，我测试了{96,192,336,720}里面的值，然后去最好。

>配置里面历史长度都是336，因为336性能最优吗还是统一都这样写。
目前这个值还不是最优的，只是统一先这么写着。过一阵子我会把能产生文章表中结果的值都传上来。

>但在benchmark测试时候是把{96,192,336,720}每种情况都测一遍？
是的，需要测试着4个不同的输入长度，且还需要为每一种长度去尽力调参（测试量还是挺大的）。

**Comment by qiu69** [comment]
同一个数据集，每个算法的结果可能是在不同历史数据长度上得到的吗?

**Comment by qiu69** [comment]
请问为什么未来预测步长只测336呢

**Comment by zezhishao** [comment]
是的

**Comment by zezhishao** [comment]
篇幅不够，我只能选择其中一个长度。

**Comment by qiu69** [comment]
好的，非常感谢
