### ISSUE TITLE
随机数

### ISSUE THREAD

**Issue by 2448845600** [zezhishao/BasicTS#84]
你好，这是个很棒的库，向您请教一些优雅的使用技巧：

在重复实验的时候，只能通过手动修改cfg文件的方式来设置random seed吗？可以将random seed的配置放到 args 中，通过shell脚本设置随机数种子？

**Comment by zezhishao** [comment]
如果您是想要做run多次，取一个平均值的话，我觉得可以这样做。

1. 删除CFG.ENV.SEED = 1
2. 添加一个CFG._=random.randint(-1e6, 1e6)

删除seed之后，每次run起来的时候结果也自然地具备随机性。
添加CFG._是为了让CFG文件的md5值变得不一样。因为BasicTS会根据CFG文件的md5来做自动logging，所以需要做这么一步。

**Comment by zezhishao** [comment]
如果您对随机数的数值没有要求，可以在配置文件中这样做:

`CFG.ENV.SEED = random.randint(-1e6, 1e6)`
